-- CreateTable
CREATE TABLE `Member` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(191) NOT NULL,
    `PASSWORD` VARCHAR(191) NOT NULL,
    `LICENSE_CODE` VARCHAR(191) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pharmacy` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `PHARMACY_NAME` VARCHAR(191) NOT NULL,
    `ADDRESS` VARCHAR(191) NOT NULL,
    `PHONE` VARCHAR(191) NOT NULL,
    `LATITUDE` DOUBLE NOT NULL,
    `LONGITUDE` DOUBLE NOT NULL,
    `OPEN_TIME` VARCHAR(191) NOT NULL,
    `CLOSE_TIME` VARCHAR(191) NOT NULL,
    `userId` INTEGER NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Medicine` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `PRODUCT_NAME` VARCHAR(191) NULL,
    `MANUFACTURER_NAME` VARCHAR(191) NULL,
    `STRENGTH_VALUE` VARCHAR(191) NULL,
    `PACK_QTY` VARCHAR(191) NULL,
    `DOSAGE_FORM` VARCHAR(191) NULL,
    `PACKAGE_TYPE` VARCHAR(191) NULL,
    `DRUG_TYPE` VARCHAR(191) NULL,
    `MAIN_CODE` VARCHAR(191) NULL,
    `STANDARD_CODE` VARCHAR(191) NULL,
    `INGREDIENT_CODE` VARCHAR(191) NULL,
    `REMARKS` VARCHAR(191) NULL,
    `ATC_CODE` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PharmacyStock` (
    `medicineId` INTEGER NOT NULL,
    `pharmacyId` INTEGER NOT NULL,
    `medCount` INTEGER NULL,

    PRIMARY KEY (`medicineId`, `pharmacyId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `StockHistory` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `pharmacyId` INTEGER NOT NULL,
    `medicineId` INTEGER NOT NULL,
    `quantity` INTEGER NOT NULL,
    `TRANSACTION_TYPE` ENUM('IN', 'OUT', 'DISCARD') NOT NULL,
    `TRANSACTION_DATE` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PharmacyBoard` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `CONTENT` VARCHAR(191) NOT NULL,
    `TITLE` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UPDATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `pharmacyId` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Pharmacy` ADD CONSTRAINT `Pharmacy_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `Member`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PharmacyStock` ADD CONSTRAINT `PharmacyStock_medicineId_fkey` FOREIGN KEY (`medicineId`) REFERENCES `Medicine`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PharmacyStock` ADD CONSTRAINT `PharmacyStock_pharmacyId_fkey` FOREIGN KEY (`pharmacyId`) REFERENCES `Pharmacy`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `StockHistory` ADD CONSTRAINT `StockHistory_pharmacyId_fkey` FOREIGN KEY (`pharmacyId`) REFERENCES `Pharmacy`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `StockHistory` ADD CONSTRAINT `StockHistory_medicineId_fkey` FOREIGN KEY (`medicineId`) REFERENCES `Medicine`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PharmacyBoard` ADD CONSTRAINT `PharmacyBoard_pharmacyId_fkey` FOREIGN KEY (`pharmacyId`) REFERENCES `Pharmacy`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
